"""test_published_vectors.py — regression pin for docs/test-vectors/.

The published vectors (docs/test-vectors/single-file.json, folder.json) are
generated by docs/test-vectors/generate.py, which produces every expected
value by EXECUTING the canonical implementation (server/engine.py,
server/merkle.py). This test re-runs the generator into a temp directory and
asserts the output matches the committed files byte-for-byte.

If this fails, one of two things happened:
  1. The engine's observable behaviour changed — a breaking change for every
     independent verifier. Regenerate the vectors in the same commit and
     say so loudly in the changelog.
  2. The committed vector files were edited by hand. Don't — regenerate.

Run: PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 python3 -m pytest tests/test_published_vectors.py -q
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VECTOR_DIR = ROOT / "docs" / "test-vectors"
GENERATOR = VECTOR_DIR / "generate.py"
VECTOR_FILES = ("single-file.json", "folder.json")


def _regenerate(tmp_path: Path) -> None:
    out = tmp_path / "vectors"
    proc = subprocess.run(
        [sys.executable, str(GENERATOR), "--out", str(out)],
        capture_output=True, text=True, timeout=120,
    )
    assert proc.returncode == 0, (
        f"generate.py failed (rc={proc.returncode}):\n{proc.stdout}\n{proc.stderr}"
    )


def test_committed_vectors_exist():
    for name in VECTOR_FILES:
        assert (VECTOR_DIR / name).is_file(), f"missing committed vector file {name}"


def test_generator_output_matches_committed_vectors(tmp_path):
    """Byte-for-byte: regeneration with an unchanged engine must be identical."""
    _regenerate(tmp_path)
    for name in VECTOR_FILES:
        committed = (VECTOR_DIR / name).read_text()
        regenerated = (tmp_path / "vectors" / name).read_text()
        assert regenerated == committed, (
            f"docs/test-vectors/{name} drifted from generate.py output — "
            "either the engine's behaviour changed (regenerate deliberately, "
            "same commit) or the committed file was hand-edited (don't)."
        )


def test_vector_suites_are_well_formed():
    """Cheap structural sanity on the committed files (no regeneration)."""
    for name in VECTOR_FILES:
        suite = json.loads((VECTOR_DIR / name).read_text())
        assert suite["format"] == "orphograph-published-vectors-v1"
        assert suite["vector_count"] == len(suite["vectors"])
        ids = [v["id"] for v in suite["vectors"]]
        assert len(ids) == len(set(ids)), f"duplicate vector ids in {name}"

    single = json.loads((VECTOR_DIR / "single-file.json").read_text())
    by_id = {v["id"]: v for v in single["vectors"]}
    # The three required negatives, with their load-bearing verdicts pinned.
    v = by_id["sf03_negative_stored_hash_uppercase"]
    assert v["operations"][-1]["expect"]["supplied_matches_receipt"] is False
    v = by_id["sf04_negative_one_byte_flipped_content"]
    assert v["operations"][-1]["expect"]["supplied_matches_receipt"] is False
    v = by_id["sf05_negative_truncated_stored_hash"]
    assert v["operations"][-1]["expect"] == {"found": False, "error": "corrupt receipt"}

    folder = json.loads((VECTOR_DIR / "folder.json").read_text())
    verdicts = {v["id"]: v["expect"]["included"] for v in folder["vectors"]}
    assert verdicts == {
        "f01_inclusion_middle_leaf": True,
        "f02_inclusion_promoted_leaf": True,
        "f03_negative_tampered_leaf_content": False,
        "f04_negative_renamed_path": False,
    }
