#!/usr/bin/env python3
"""route_sweep.py — Stage 3i classifier for the `routes` domain.

Takes the domain from `enumerate_surface.py routes` (refuses to run when its
oracles fail) and classifies every element against production for ONE defect
class: a dispatched path must answer GET and HEAD with the same status, and both
answers must carry HSTS and `X-Content-Type-Options: nosniff`. That is the class
of the 2026-08-07 HEAD/501 incident, where one method bug manufactured three
external security findings.

What SAFE does and does not mean — say it in the manifest prose too:
  - eq routes are probed at their literal path;
  - prefix routes are route FAMILIES; the probe is a synthesized member
    (`<prefix>sweep-probe<suffix>`), which exercises the handler's not-found
    branch, NOT its behaviour on valid input;
  - POST-only routes are probed with GET/HEAD only. Nothing here sends a body,
    a POST, or a credential. SAFE = method parity + two transport headers.

Verdicts:
  UNKNOWN  no answer, 429, Cloudflare 52x/530, or a Cloudflare-generated 403 —
           infrastructure answered, the application did not (Stage 3h LEAKED
           arm). Never folded into SAFE. Non-SAFE paths are re-probed at the
           Fly origin so edge answers and app answers can be told apart.
  FINDING  GET/HEAD status differ, or HSTS / nosniff missing on either.
  SAFE     otherwise.

Control: after the live pass, HSTS is stripped from the recorded HEAD answer of
one MEMBER path (default /api/health) and the classifier must flip it to
FINDING. A control that is not a member, or is not caught, voids the sweep.

Exit codes:
  0  manifest printed (control caught, UNKNOWN within --max-unknown)
  1  findings remain, control failed, or too many UNKNOWN — not passing
  3  the routes enumeration failed its oracles or could not run
"""
from __future__ import annotations

import argparse
import json
import socket
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import enumerate_surface as es  # noqa: E402

UA = "orphograph-tooling/1.0 (+https://orphograph.com)"   # honest UA, never a browser string
MEMBER = "sweep-probe"
INFRA_STATUS = {429, 520, 521, 522, 523, 524, 525, 526, 527, 530}
HEADERS = (("strict-transport-security", "HSTS"), ("x-content-type-options", "nosniff"))


class _NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, *args, **kwargs):   # parity compares the raw answer
        return None


_OPENER = urllib.request.build_opener(_NoRedirect)


def probe_path(el: dict) -> str:
    lit, suffix = el["literal"], el.get("suffix") or ""
    if el["kind"] == "eq":
        return lit
    return (lit + MEMBER + suffix) if lit.endswith("/") else (lit + suffix)


def fetch(base: str, path: str, method: str, timeout: float) -> dict:
    req = urllib.request.Request(base + path, method=method, headers={"User-Agent": UA})
    try:
        with _OPENER.open(req, timeout=timeout) as r:
            return dict(status=r.status, headers={k.lower(): v for k, v in r.headers.items()})
    except urllib.error.HTTPError as e:
        return dict(status=e.code, headers={k.lower(): v for k, v in (e.headers or {}).items()})
    except (urllib.error.URLError, socket.timeout, TimeoutError, OSError) as e:
        return dict(status=None, headers={}, error=type(e).__name__)


def classify(get: dict, head: dict) -> tuple[str, str]:
    for name, r in (("GET", get), ("HEAD", head)):
        status, hdrs = r.get("status"), r.get("headers") or {}
        if status is None:
            return "UNKNOWN", f"{name} no answer ({r.get('error')})"
        # A status code alone does not say WHO answered. The app's own 429 (its rate
        # limiter) and 403 carry the security bundle; a Cloudflare-generated one does
        # not. Found 2026-09-12: the app's limiter 429'd /api/nowpayments/order/* after
        # repeated sweeps, WITH HSTS+nosniff, and was misfiled as infrastructure.
        app_answered = "strict-transport-security" in hdrs
        if status in INFRA_STATUS and not (status in (403, 429) and app_answered):
            return "UNKNOWN", f"{name} {status}: infrastructure answered"
        if status == 403 and hdrs.get("server", "").lower() == "cloudflare" and not app_answered:
            return "UNKNOWN", f"{name} 403 generated by Cloudflare, not the app"
    if get["status"] != head["status"] and 429 in (get["status"], head["status"]):
        return "UNKNOWN", "rate-limit boundary prevents a method-parity comparison"
    if get["status"] != head["status"]:
        return "FINDING", f"parity: GET {get['status']} != HEAD {head['status']}"
    for header, label in HEADERS:
        missing = [n for n, r in (("GET", get), ("HEAD", head)) if header not in (r.get("headers") or {})]
        if missing:
            return "FINDING", f"{label} missing on {'+'.join(missing)} (status {get['status']})"
    return "SAFE", f"GET=HEAD={get['status']}, HSTS+nosniff on both"


def sweep(elements: list[dict], base: str, origin: str | None, pace: float, timeout: float,
          fetcher=fetch, sleep=time.sleep) -> dict[str, dict]:
    results: dict[str, dict] = {}
    paths = sorted({probe_path(e) for e in elements})
    for i, p in enumerate(paths, 1):
        g = fetcher(base, p, "GET", timeout)
        sleep(pace)
        h = fetcher(base, p, "HEAD", timeout)
        sleep(pace)
        verdict, why = classify(g, h)
        row = dict(path=p, verdict=verdict, why=why, get=g.get("status"), head=h.get("status"), raw=(g, h))
        if verdict != "SAFE" and origin:
            og = fetcher(origin, p, "GET", timeout)
            sleep(pace)
            oh = fetcher(origin, p, "HEAD", timeout)
            sleep(pace)
            row["origin"] = dict(zip(("verdict", "why"), classify(og, oh)))
        results[p] = row
        print(f"[{i}/{len(paths)}] {verdict:<7} {p}  {why}", file=sys.stderr)
    return results


def plant_control(results: dict[str, dict], path: str) -> tuple[bool, str]:
    if path not in results:
        return False, f"control {path} is not a member of the domain"
    get, head = results[path]["raw"]
    stripped = dict(head, headers={k: v for k, v in (head.get("headers") or {}).items()
                                   if k != "strict-transport-security"})
    verdict, why = classify(get, stripped)
    return verdict == "FINDING", why


def summarize(elements: list[dict], results: dict[str, dict]) -> dict[str, int]:
    counts = {"SAFE": 0, "FINDING": 0, "UNKNOWN": 0}
    for e in elements:
        counts[results[probe_path(e)]["verdict"]] += 1
    return counts


def manifest(n: int, counts: dict[str, int], control: str) -> str:
    return (f"<!-- SWEEP-MANIFEST v1 domain=routes surfaces={n} classified={sum(counts.values())} "
            f"safe={counts['SAFE']} finding={counts['FINDING']} unknown={counts['UNKNOWN']} "
            f"repro={counts['FINDING']} fixed=0 control={control} -->")


def selftest() -> int:
    fails, ran = [], []

    def check(name, cond):
        ran.append(name)
        if not cond:
            fails.append(name)

    ok = {"strict-transport-security": "max-age=1", "x-content-type-options": "nosniff"}
    r = lambda s, h=ok: dict(status=s, headers=dict(h))
    check("safe", classify(r(200), r(200))[0] == "SAFE")
    check("405 parity is safe (no status rule)", classify(r(405), r(405))[0] == "SAFE")
    check("parity finding", classify(r(200), r(501, {}))[0] == "FINDING")
    check("hsts missing on HEAD only", classify(r(200), r(200, {"x-content-type-options": "nosniff"}))
          == ("FINDING", "HSTS missing on HEAD (status 200)"))
    check("bare 429 without app headers is unknown", classify(r(429, {}), r(429, {}))[0] == "UNKNOWN")
    check("app 429 carrying the security bundle is judged", classify(r(429), r(429))[0] == "SAFE")
    check("rate-limit boundary is inconclusive", classify(r(429), r(200))[0] == "UNKNOWN")
    check("52x stays unknown even with headers", classify(r(522), r(522))[0] == "UNKNOWN")
    check("no answer unknown", classify(dict(status=None, headers={}, error="timeout"), r(200))[0] == "UNKNOWN")
    check("cloudflare 403 unknown", classify(r(403, {"server": "cloudflare"}), r(403, {"server": "cloudflare"}))[0] == "UNKNOWN")
    check("app 403 with headers is judged", classify(r(403, dict(ok, server="cloudflare")), r(403, dict(ok, server="cloudflare")))[0] == "SAFE")

    els = [dict(method="GET", kind="eq", literal="/api/health", suffix=None),
           dict(method="GET", kind="prefix", literal="/api/badge/", suffix=".svg"),
           dict(method="POST", kind="eq", literal="/api/anchor", suffix=None),
           dict(method="GET", kind="prefix", literal="/pay/crypto", suffix=None)]
    check("probe paths", [probe_path(e) for e in els]
          == ["/api/health", "/api/badge/sweep-probe.svg", "/api/anchor", "/pay/crypto"])

    answers = {"/api/health": (r(200), r(200)), "/api/badge/sweep-probe.svg": (r(404), r(404)),
               "/api/anchor": (r(404), r(404, {})), "/pay/crypto": (r(429, {}), r(200))}
    calls = []

    def fake(base, path, method, timeout):
        calls.append((base, method))
        return answers[path][0 if method == "GET" else 1]

    res = sweep(els, "https://edge", "https://origin", 0, 1, fetcher=fake, sleep=lambda s: None)
    counts = summarize(els, res)
    check("counts", counts == {"SAFE": 2, "FINDING": 1, "UNKNOWN": 1})
    check("non-safe re-probed at origin, safe not", sum(1 for b, _ in calls if b == "https://origin") == 4)
    check("control caught on a SAFE member", plant_control(res, "/api/health")[0])
    check("control outside the domain voids", not plant_control(res, "/not-a-member")[0])
    m = manifest(len(els), counts, "hsts-stripped:/api/health")
    check("manifest balances", "surfaces=4 classified=4 safe=2 finding=1 unknown=1 repro=1 fixed=0" in m)

    for f in fails:
        print(f"SELFTEST FAIL: {f}", file=sys.stderr)
    print(f"selftest: {len(ran) - len(fails)}/{len(ran)} cases pass")
    return 1 if fails else 0


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("repo", nargs="?", default=str(Path(__file__).resolve().parents[1]))
    ap.add_argument("ref", nargs="?", default="HEAD")
    ap.add_argument("--base", default="https://orphograph.com")
    ap.add_argument("--origin", default="https://orphograph.fly.dev")
    ap.add_argument("--pace", type=float, default=0.5)
    ap.add_argument("--timeout", type=float, default=30.0)
    ap.add_argument("--control", default="/api/health")
    ap.add_argument("--max-unknown", type=int, default=5)
    ap.add_argument("--out", help="write per-path results as JSON")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args(argv[1:])
    if a.selftest:
        return selftest()

    try:
        rep = es.enumerate_routes(Path(a.repo).expanduser(), a.ref)
    except (RuntimeError, OSError, SyntaxError) as e:
        print(f"cannot enumerate routes: {e}", file=sys.stderr)
        return 3
    if not rep["ok"]:
        print("routes enumeration failed its oracles — refusing to sweep "
              "(run enumerate_surface.py routes for the reasons)", file=sys.stderr)
        return 3

    elements = rep["elements"]
    results = sweep(elements, a.base, a.origin, a.pace, a.timeout)
    counts = summarize(elements, results)
    caught, why = plant_control(results, a.control)
    if a.out:
        Path(a.out).write_text(json.dumps(
            dict(elements=elements, counts=counts, control=dict(path=a.control, caught=caught, why=why),
                 results={p: {k: v for k, v in row.items() if k != "raw"} for p, row in results.items()}),
            indent=2))

    for p, row in sorted(results.items()):
        if row["verdict"] != "SAFE":
            origin = row.get("origin", {})
            print(f"{row['verdict']}  {p}  edge: {row['why']}  origin: {origin.get('verdict')} {origin.get('why', '')}")
            if row["verdict"] == "FINDING":
                print(f"  repro: curl -sS -o /dev/null -D - -A '{UA}' {a.base}{p} ; "
                      f"curl -sS -o /dev/null -D - -I -A '{UA}' {a.base}{p}")
    print(f"elements={len(elements)} paths={len(results)} counts={counts} "
          f"control={a.control} caught={caught} ({why})")
    if not caught:
        print("CONTROL NOT CAUGHT — sweep UNVERIFIED, no manifest.", file=sys.stderr)
        return 1
    if counts["UNKNOWN"] > a.max_unknown:
        print(f"UNKNOWN {counts['UNKNOWN']} > {a.max_unknown} — infrastructure answered too often; "
              f"slow down and re-run, do not report totality.", file=sys.stderr)
        return 1
    if counts["FINDING"]:
        print("Route findings remain — CI gate failed.", file=sys.stderr)
        return 1
    print(manifest(len(elements), counts, "hsts-stripped:" + a.control.strip("/").replace("/", "-")))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
